package gui;

import data.Material;
import data.Preset;
import data.Product;
import data.types.TypeArea;
import data.types.TypeLength;
import data.types.TypePiece;
import data.types.TypeVolume;
import gui.model.PresetListModel;
import gui.model.ProductModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author emil
 */
public class AddProductDialog extends javax.swing.JDialog {
    
    private boolean pressedOk = false;
    private Product product = new Product();
    private ProductModel productModel = new ProductModel(product);
    private final PresetListModel presetListModel = new PresetListModel();
    private data.types.Type currentType;

    /**
     * Creates new form AddProductDialog
     */
    public AddProductDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("Produkt hinzufügen...");
        setLocationRelativeTo(parent);
        
        jTableMaterials.setModel(productModel);
        jListPresets.setModel(presetListModel);
        
        jLabelFirst.setText("Wert:");
        jLabelSecond.setText("Wert:");
        jLabelThird.setText("Wert:");
    }

    public boolean isPressedOk() {
        return pressedOk;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
        productModel = new ProductModel(product);
        jTableMaterials.setModel(productModel);
        productModel.fireTableDataChanged();
        jtfName.setText(product.getName());
        jtfHours.setValue(product.getHours());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterials = new javax.swing.JTable();
        jPanButtons = new javax.swing.JPanel();
        jbutOK = new javax.swing.JButton();
        jbutCancel = new javax.swing.JButton();
        jPanEast = new javax.swing.JPanel();
        jPanControls = new javax.swing.JPanel();
        jLabelPreset = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPresets = new javax.swing.JList<>();
        jbutAdd = new javax.swing.JButton();
        jbutRemove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelFirst = new javax.swing.JLabel();
        jLabelSecond = new javax.swing.JLabel();
        jLabelThird = new javax.swing.JLabel();
        jtfFirst = new javax.swing.JFormattedTextField();
        jtfSecond = new javax.swing.JFormattedTextField();
        jtfThird = new javax.swing.JFormattedTextField();
        jPanControls1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelHours = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfHours = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTableMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterials);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanButtons.setBackground(new java.awt.Color(255, 255, 255));
        jPanButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanButtons.setLayout(new java.awt.GridLayout(1, 0));

        jbutOK.setText("OK");
        jbutOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutOKActionPerformed(evt);
            }
        });
        jPanButtons.add(jbutOK);

        jbutCancel.setText("Abbrechen");
        jbutCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutCancelActionPerformed(evt);
            }
        });
        jPanButtons.add(jbutCancel);

        getContentPane().add(jPanButtons, java.awt.BorderLayout.SOUTH);

        jPanEast.setBackground(new java.awt.Color(255, 255, 255));
        jPanEast.setLayout(new java.awt.GridBagLayout());

        jPanControls.setBackground(new java.awt.Color(255, 255, 255));
        jPanControls.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Material")));
        jPanControls.setLayout(new java.awt.GridBagLayout());

        jLabelPreset.setText("Vorlage:");
        jLabelPreset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanControls.add(jLabelPreset, gridBagConstraints);

        jListPresets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onPresetList(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onMousePresetList(evt);
            }
        });
        jScrollPane2.setViewportView(jListPresets);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        jPanControls.add(jScrollPane2, gridBagConstraints);

        jbutAdd.setText("Hinzufügen");
        jbutAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanControls.add(jbutAdd, gridBagConstraints);

        jbutRemove.setText("Entfernen");
        jbutRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutRemoveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanControls.add(jbutRemove, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabelFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFirst.setText("First");
        jLabelFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelFirst);

        jLabelSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSecond.setText("Second");
        jLabelSecond.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelSecond);

        jLabelThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThird.setText("Third");
        jLabelThird.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelThird);

        jtfFirst.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(jtfFirst);

        jtfSecond.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(jtfSecond);

        jtfThird.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(jtfThird);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanControls.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanEast.add(jPanControls, gridBagConstraints);

        jPanControls1.setBackground(new java.awt.Color(255, 255, 255));
        jPanControls1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Produkt")));
        jPanControls1.setLayout(new java.awt.GridBagLayout());

        jLabelName.setText("Produktname:");
        jPanControls1.add(jLabelName, new java.awt.GridBagConstraints());

        jLabelHours.setText("Arbeitsstunden:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanControls1.add(jLabelHours, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanControls1.add(jtfName, gridBagConstraints);

        jtfHours.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanControls1.add(jtfHours, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanEast.add(jPanControls1, gridBagConstraints);

        getContentPane().add(jPanEast, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutAddActionPerformed
        try {
            Preset preset = jListPresets.getSelectedValue();
            
            double first = 0;
            double second = 0;
            double third = 0;
            
            first = ((Number)jtfFirst.getValue()).doubleValue();
            if (currentType instanceof TypeArea || currentType instanceof TypeVolume) {
                second = ((Number)jtfSecond.getValue()).doubleValue();
            }
            if (currentType instanceof TypeVolume) {
                third = ((Number)jtfThird.getValue()).doubleValue();
            }
            
            double value = currentType.calcValue(new double[] {first, second, third});
            
            product.add(new Material(preset, value));
            productModel.fireTableDataChanged();
            jtfFirst.setValue(null);
            jtfSecond.setValue(null);
            jtfThird.setValue(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bitte alle Felder korrekt ausfüllen!", "Fehler!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbutAddActionPerformed

    private void jbutRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutRemoveActionPerformed
        product.remove(jTableMaterials.getSelectedRow());
        productModel.fireTableDataChanged();
    }//GEN-LAST:event_jbutRemoveActionPerformed

    private void jbutOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutOKActionPerformed
        if (jtfName.getText().isEmpty() || product.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bitte das Produkt benennen und Materialien hinzufügen.", "Fehler!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                product.setName(jtfName.getText());
                product.setHours(((Number)jtfHours.getValue()).doubleValue());
                pressedOk = true;
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Eingaben überprüfen!", "Fehler aufgetreten!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbutOKActionPerformed

    private void jbutCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutCancelActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Wollen Sie wirklich abbrechen?", "Warnung - Abbruch", JOptionPane.WARNING_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jbutCancelActionPerformed

    private void onPresetList(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPresetList
        String text1 = null;
        String text2 = null;
        String text3 = null;
        if (jListPresets.getSelectedValue() == null) {
            return;
        }
        Preset preset = jListPresets.getSelectedValue();
        currentType = preset.getType();
        
        if (currentType instanceof TypeArea) {
            text1 = "Länge:";
            text2 = "Breite:";
            jLabelSecond.setVisible(true);
            jtfSecond.setVisible(true);
            jLabelThird.setVisible(false);
            jtfThird.setVisible(false);
        } else if (currentType instanceof TypeLength) {
            text1 = "Länge:";
            jLabelSecond.setVisible(false);
            jtfSecond.setVisible(false);
            jLabelThird.setVisible(false);
            jtfThird.setVisible(false);
        } else if (currentType instanceof TypePiece) {
            text1 = "Anzahl:";
            jLabelSecond.setVisible(false);
            jtfSecond.setVisible(false);
            jLabelThird.setVisible(false);
            jtfThird.setVisible(false);
        } else if (currentType instanceof TypeVolume) {
            text1 = "Länge:";
            text2 = "Breite:";
            text3 = "Höhe";
            jLabelSecond.setVisible(true);
            jtfSecond.setVisible(true);
            jLabelThird.setVisible(true);
            jtfThird.setVisible(true);
        }
        
        jLabelFirst.setText(text1);
        jLabelSecond.setText(text2);
        jLabelThird.setText(text3);
    }//GEN-LAST:event_onPresetList

    private void onMousePresetList(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMousePresetList
        onPresetList(evt);
    }//GEN-LAST:event_onMousePresetList

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Woody.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            AddProductDialog dialog = new AddProductDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelHours;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPreset;
    private javax.swing.JLabel jLabelSecond;
    private javax.swing.JLabel jLabelThird;
    private javax.swing.JList<Preset> jListPresets;
    private javax.swing.JPanel jPanButtons;
    private javax.swing.JPanel jPanControls;
    private javax.swing.JPanel jPanControls1;
    private javax.swing.JPanel jPanEast;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMaterials;
    private javax.swing.JButton jbutAdd;
    private javax.swing.JButton jbutCancel;
    private javax.swing.JButton jbutOK;
    private javax.swing.JButton jbutRemove;
    private javax.swing.JFormattedTextField jtfFirst;
    private javax.swing.JFormattedTextField jtfHours;
    private javax.swing.JTextField jtfName;
    private javax.swing.JFormattedTextField jtfSecond;
    private javax.swing.JFormattedTextField jtfThird;
    // End of variables declaration//GEN-END:variables
}
